"""
Django settings for UniMarketPRJ project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from decouple import config  # pip install decouple

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

# Media파일 사용 설정
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 로그
# 아래 로그의 순으로 해당 로그를 선택하면 그 아래부터 전부 저장됨
# ex) logger.info()를 선택하면 아래 wrning(), error(), critical()도 함께 선택된 격
# logger.debug()    # 디버그
# logger.info()    # 정보
# logger.warning()    # 심하지않은 에러
# logger.error()    # 에러
# logger.critical()    # 매우심한 에러
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "format1": {
            "format": "[%(asctime)s]%(levelname)s [%(name)s:%(lineno)s]%(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "format2": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "log/logfile.log"),
            "encoding": "UTF-8",
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 5,
            "formatter": "format1",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "format2",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "propagate": True,
            "level": "WARNING",
        },
        "django.request": {
            "handlers": ["console"],
            "propagate": True,
            "level": "WARNING",
        },
        "unimarket": {
            "handlers": ["file"],
            "propagate": True,
            "level": "INFO",
        },
        "itemMarkUpdater": {
            "handlers": ["file"],
            "propagate": True,
            "level": "INFO",
        },
        "chat": {
            "handlers": ["file"],
            "propagate": True,
            "level": "INFO",
        },
    },
}


SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
ALGORITHM = config("ALGORITHM")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

V3_SITE_KEY = config("V3_SITE_KEY")
V3_SECRET_KEY = config("V3_SECRET_KEY")

# 카카오 appkey
KAKAO_MAP = config("KAKAO_MAP")

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "channels",  # 채팅을 위한 설정
    "chat",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "unimarket.apps.UnimarketConfig",  # 설정값이 필요할 경우 해당 형식으로 선언
    "mathfilters",  # 계산을 위한 패키지 앱으로 등록
    "django_apscheduler",  # 일주일이상 등록된 상품, 공지사항을 사용자들에게 주기적 알림을 위한 패키지
]

# django_apscheduler 사용을 위한 설정
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"  # Default
SCHEDULER_DEFAULT = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "UniMarketPRJ.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates/")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# Channels
ASGI_APPLICATION = "UniMarketPRJ.asgi.application"
# Channel layers
# CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

WSGI_APPLICATION = "UniMarketPRJ.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# 지환
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # 메일 호스트 서버
EMAIL_PORT = 587  # 서버 포트
EMAIL_USE_TLS = True  # TLS 보안 설정
# EMAIL_PORT = 25                                     # 서버 포트
# EMAIL_USE_SSL = True                                # SSL 보안 설정
EMAIL_HOST_USER = "unimarketprj1@gmail.com"  # 우리가 사용할 Gmail
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # 우리가 사용할 Gmail pw
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# reset link https가 http로 갈경우 이동 경로 재설정
# SECURE_SSL_REDIRECT = True

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "ko"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
