# Generated by Django 4.0.1 on 2022-03-17 04:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catNo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='카테고리번호')),
                ('catName', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('catLogo', models.CharField(max_length=20, null=True, verbose_name='카테고리로고')),
            ],
        ),
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatNo', models.CharField(max_length=20, verbose_name='챗번호')),
                ('itemNo', models.CharField(max_length=10, verbose_name='상품번호')),
                ('sellMemNo', models.IntegerField(default=0, verbose_name='판매자회원번호')),
                ('buyMemNo', models.IntegerField(default=0, verbose_name='거래자회원번호')),
                ('fromSender', models.IntegerField(default=0, verbose_name='보낸사람회원번호')),
                ('chatContent', models.TextField(max_length=2000, verbose_name='챗내용')),
                ('chatRead', models.IntegerField(default=0, verbose_name='읽음여부')),
                ('endTime', models.DateTimeField(auto_now_add=True, verbose_name='보낸일시')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatNo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='챗번호')),
                ('sellMemNo', models.IntegerField(null=True, verbose_name='판매자회원번호')),
                ('buyMemNo', models.IntegerField(null=True, verbose_name='거래자회원번호')),
                ('itemNo', models.CharField(default='', max_length=10, verbose_name='상품번호')),
                ('title', models.CharField(default='', max_length=200, verbose_name='제목')),
                ('itemImg', models.ImageField(null=True, upload_to='item/%Y/%m/%d', verbose_name='상품이미지')),
                ('sendTime', models.DateTimeField(auto_now_add=True, verbose_name='보낸일시')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스번호')),
                ('questions', models.CharField(max_length=100, verbose_name='질문')),
                ('answer', models.CharField(max_length=500, verbose_name='답변')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemNo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='상품번호')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('catNo', models.CharField(max_length=10, verbose_name='카테고리번호')),
                ('memNo', models.IntegerField(verbose_name='회원번호')),
                ('loc', models.CharField(max_length=80, verbose_name='지역')),
                ('zonecode', models.CharField(default=0, max_length=10, verbose_name='우편번호')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('info', models.TextField(max_length=2000, verbose_name='상품설명')),
                ('uDate', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('readCnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('likeCnt', models.IntegerField(default=0, verbose_name='찜수')),
                ('itemImg', models.ImageField(blank=True, null=True, upload_to='item/%Y/%m/%d', verbose_name='상품이미지')),
                ('sellStat', models.IntegerField(default=0, verbose_name='판매완료유무')),
                ('sellDate', models.DateTimeField(blank=True, null=True, verbose_name='판매완료일')),
                ('buyMemNo', models.IntegerField(default=0, verbose_name='구매자')),
                ('SatisfactionAvg', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2, verbose_name='추천상품만족도평균')),
                ('reviewed', models.IntegerField(default=0, verbose_name='리뷰완료상태')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='찜번호')),
                ('memNo', models.IntegerField(verbose_name='회원번호')),
                ('itemNo', models.CharField(max_length=10, verbose_name='상품번호')),
                ('price', models.IntegerField(verbose_name='가격')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스번호')),
                ('markNo', models.CharField(max_length=20, verbose_name='알림번호')),
                ('memNo', models.IntegerField(verbose_name='회원번호')),
                ('markStat', models.IntegerField(default=0, verbose_name='알림상태')),
                ('markContent', models.CharField(max_length=80, verbose_name='알림문구')),
                ('markDate', models.DateTimeField(auto_now_add=True, verbose_name='알림일')),
                ('markRead', models.IntegerField(default=0, verbose_name='읽음여부')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memNo', models.AutoField(primary_key=True, serialize=False, verbose_name='회원번호')),
                ('email', models.EmailField(max_length=50, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('passwd', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('bDate', models.DateTimeField(verbose_name='생년월일')),
                ('loc', models.CharField(max_length=80, verbose_name='지역')),
                ('zonecode', models.CharField(default=0, max_length=10, verbose_name='우편번호')),
                ('gender', models.IntegerField(verbose_name='성별')),
                ('marrStat', models.IntegerField(verbose_name='결혼유무')),
                ('proImg', models.ImageField(blank=True, null=True, upload_to='pro/%Y/%m/%d', verbose_name='프로필아이콘')),
                ('report', models.IntegerField(default=0, verbose_name='신고받은유무')),
                ('rGrade', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2, verbose_name='별점평균')),
                ('reportCnt', models.IntegerField(default=0, verbose_name='신고받은횟수')),
                ('memStat', models.IntegerField(default=1, verbose_name='회원상태')),
                ('reviewCnt', models.IntegerField(default=0, verbose_name='리뷰받은횟수')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스번호')),
                ('noticeNo', models.CharField(max_length=20, verbose_name='공지번호')),
                ('noticeTitle', models.CharField(default='공지', max_length=200, verbose_name='공지제목')),
                ('noticeContent', models.TextField(max_length=2000, verbose_name='공지내용')),
                ('eventImg', models.ImageField(blank=True, null=True, upload_to='event/%Y/%m/%d', verbose_name='이벤트이미지')),
                ('noticeDate', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
        migrations.CreateModel(
            name='PerfectUpdateday',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스번호')),
                ('testday', models.DateField(verbose_name='검증한날')),
                ('testresult', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='검증결과')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='신고번호')),
                ('reportFrom', models.IntegerField(verbose_name='신고자회원번호')),
                ('reportTo', models.IntegerField(verbose_name='신고받은회원번호')),
                ('reportContent', models.TextField(max_length=2000, verbose_name='신고내용')),
                ('reportDate', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('itemNo', models.CharField(max_length=10, verbose_name='상품번호')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스번호')),
                ('memNo', models.IntegerField(verbose_name='판매회원번호')),
                ('buyMemNo', models.IntegerField(verbose_name='구매회원번호')),
                ('description', models.IntegerField(default=0, verbose_name='설명점수')),
                ('condition', models.IntegerField(default=0, verbose_name='상태점수')),
                ('priceScore', models.IntegerField(default=0, verbose_name='가격점수')),
                ('attitude', models.IntegerField(default=0, verbose_name='태도점수')),
                ('distance', models.IntegerField(default=0, verbose_name='거리점수')),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스번호')),
                ('itemNo', models.CharField(max_length=10, verbose_name='상품번호')),
                ('memNo', models.IntegerField(verbose_name='회원번호')),
                ('satisfactionScore', models.IntegerField(default=0, verbose_name='만족도점수')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스번호')),
                ('memNo', models.IntegerField(verbose_name='회원번호')),
                ('searchKey', models.CharField(max_length=30, verbose_name='키워드')),
                ('loc', models.CharField(max_length=80, verbose_name='지역')),
                ('zonecode', models.CharField(default=0, max_length=10, verbose_name='우편번호')),
                ('searchDate', models.DateTimeField(auto_now_add=True, verbose_name='검색일')),
            ],
        ),
        migrations.CreateModel(
            name='StayLog',
            fields=[
                ('indexNo', models.AutoField(primary_key=True, serialize=False, verbose_name='인덱스번호')),
                ('memNo', models.IntegerField(verbose_name='회원번호')),
                ('itemNo', models.CharField(max_length=10, verbose_name='상품번호')),
                ('connectDate', models.DateTimeField(auto_now_add=True, verbose_name='접속시간')),
                ('stayCnt', models.IntegerField(default=0, verbose_name='10분기준머문횟수')),
                ('stayTime', models.IntegerField(default=0, verbose_name='실제머문시간')),
                ('stayFlg', models.IntegerField(default=0, verbose_name='새로고침여부')),
            ],
        ),
    ]
